/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class ConsPacienteInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsPacienteInternalFrame
     */
    public Controlador.GestorPacienteControl gestorpacienteControl;
    private DefaultTableModel tabla;
    public ConsPacienteInternalFrame() {
        initComponents();
        gestorpacienteControl =new Controlador.GestorPacienteControl(this);
        String titulosTabla[]={"Identificacion","Nombres","Apelllidos","Fecha Nacimiento", "Genero"};     
        tabla=new DefaultTableModel(null, titulosTabla);
        tblDatos.setModel(tabla);
        jButton1.addActionListener(gestorpacienteControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrIdentificacion = new javax.swing.JRadioButton();
        jrNombre = new javax.swing.JRadioButton();
        jrApellido = new javax.swing.JRadioButton();
        jrSexo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Pacientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrIdentificacion.setText("Identificacion");
        jrIdentificacion.setOpaque(false);
        jPanel1.add(jrIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 15, -1, -1));

        jrNombre.setText("Nombres");
        jrNombre.setOpaque(false);
        jPanel1.add(jrNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 15, -1, -1));

        jrApellido.setText("Apellidos");
        jrApellido.setOpaque(false);
        jPanel1.add(jrApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 15, -1, -1));

        jrSexo.setText("Genero");
        jrSexo.setOpaque(false);
        jrSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSexoActionPerformed(evt);
            }
        });
        jPanel1.add(jrSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 15, -1, -1));

        jLabel1.setText("Valor a buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, -1));

        jButton1.setText("Aceptar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 56, -1, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 447, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/medico-receta-al-paciente-pildora-botella-mujer-consulta-medico-mientras-sentado-mesa_8119-2504.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 590, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 1, -1, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton jrApellido;
    public javax.swing.JRadioButton jrIdentificacion;
    public javax.swing.JRadioButton jrNombre;
    public javax.swing.JRadioButton jrSexo;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
