/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class ConsTratamientoInternalFrame extends javax.swing.JInternalFrame {

    public Controlador.GestorTratamientoControl gestortratamientoControl;
    private DefaultTableModel tabla;
    public ConsTratamientoInternalFrame() {
        initComponents();
        gestortratamientoControl =new Controlador.GestorTratamientoControl(this);
        String titulosTabla[]={"Identificacion","Nombres","Apelllidos","Fecha Nacimiento", "Genero"};     
        tabla=new DefaultTableModel(null, titulosTabla);
        jtConsTratamiento.setModel(tabla);
        btnTraBuscar.addActionListener(gestortratamientoControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrTratamiento = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        label1 = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jrCodiTratamiento = new javax.swing.JRadioButton();
        jrFeAsignacion = new javax.swing.JRadioButton();
        jrFeInicio = new javax.swing.JRadioButton();
        jrFeFinal = new javax.swing.JRadioButton();
        jrDesTratamiento = new javax.swing.JRadioButton();
        jrIdenPaciente = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtTraValor = new javax.swing.JTextField();
        btnTraBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsTratamiento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        label1.setText("label1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar tratamiento");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btgrTratamiento.add(jrCodiTratamiento);
        jrCodiTratamiento.setText("Codigo tratamiento");
        jrCodiTratamiento.setOpaque(false);
        jPanel1.add(jrCodiTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btgrTratamiento.add(jrFeAsignacion);
        jrFeAsignacion.setText("Fecha asignacion");
        jrFeAsignacion.setOpaque(false);
        jPanel1.add(jrFeAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        btgrTratamiento.add(jrFeInicio);
        jrFeInicio.setText("Fecha inicio tratamiento");
        jrFeInicio.setOpaque(false);
        jPanel1.add(jrFeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btgrTratamiento.add(jrFeFinal);
        jrFeFinal.setText("Fecha final tratamiento");
        jrFeFinal.setOpaque(false);
        jPanel1.add(jrFeFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btgrTratamiento.add(jrDesTratamiento);
        jrDesTratamiento.setText("Descripcion tratamiento");
        jrDesTratamiento.setOpaque(false);
        jPanel1.add(jrDesTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        btgrTratamiento.add(jrIdenPaciente);
        jrIdenPaciente.setText("Identificacion paciente");
        jrIdenPaciente.setOpaque(false);
        jPanel1.add(jrIdenPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Valor a buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(txtTraValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 20));

        btnTraBuscar.setText("Buscar");
        btnTraBuscar.setOpaque(false);
        jPanel1.add(btnTraBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jtConsTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtConsTratamiento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 400, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/calendario-tratamiento-medico-gestion-tiempo_23-2148438973.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 590, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrTratamiento;
    public javax.swing.JButton btnTraBuscar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton jrCodiTratamiento;
    public javax.swing.JRadioButton jrDesTratamiento;
    public javax.swing.JRadioButton jrFeAsignacion;
    public javax.swing.JRadioButton jrFeFinal;
    public javax.swing.JRadioButton jrFeInicio;
    public javax.swing.JRadioButton jrIdenPaciente;
    public javax.swing.JTable jtConsTratamiento;
    private java.awt.Label label1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    public javax.swing.JTextField txtTraValor;
    // End of variables declaration//GEN-END:variables
}
