/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class ConsMedicoInternalFrame extends javax.swing.JInternalFrame {

    public Controlador.GestorMedicoControl gestormedicoControl;
    private DefaultTableModel tablaMe;
    
    public ConsMedicoInternalFrame() {
        initComponents();
        gestormedicoControl =new Controlador.GestorMedicoControl(this);
        String titulosTabla[]={"Identificacion","Nombres","Apelllidos","Fecha Nacimiento", "Genero"};     
        tablaMe=new DefaultTableModel(null, titulosTabla);
        jtMedicos.setModel(tablaMe);
        btnBuscar.addActionListener(gestormedicoControl);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrMeBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMedicos = new javax.swing.JTable();
        jrMeIdentificacion = new javax.swing.JRadioButton();
        jrMeNombre = new javax.swing.JRadioButton();
        jrMeApellido = new javax.swing.JRadioButton();
        txtMeValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Medico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtMedicos.setOpaque(false);
        jScrollPane1.setViewportView(jtMedicos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 100));

        btngrMeBusqueda.add(jrMeIdentificacion);
        jrMeIdentificacion.setText("Identificacion");
        jrMeIdentificacion.setOpaque(false);
        jPanel1.add(jrMeIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btngrMeBusqueda.add(jrMeNombre);
        jrMeNombre.setText("Nombre");
        jrMeNombre.setOpaque(false);
        jPanel1.add(jrMeNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        btngrMeBusqueda.add(jrMeApellido);
        jrMeApellido.setText("Apellido");
        jrMeApellido.setOpaque(false);
        jPanel1.add(jrMeApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));
        jPanel1.add(txtMeValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, -1));

        jLabel2.setText("Valor a buscar: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/doctor-estetoscopio-formulario-medico_23-2148454284.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 570, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btngrMeBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton jrMeApellido;
    public javax.swing.JRadioButton jrMeIdentificacion;
    public javax.swing.JRadioButton jrMeNombre;
    public javax.swing.JTable jtMedicos;
    public javax.swing.JTextField txtMeValor;
    // End of variables declaration//GEN-END:variables
}
