/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author maria
 */
public class RegCitasInternalFrame extends javax.swing.JInternalFrame {

     private Controlador.CitasControl citasControlador;
    
    public RegCitasInternalFrame() {
        initComponents();
        citasControlador  = new Controlador.CitasControl(this);
        btnRegisCita.addActionListener(citasControlador);
        btnNuevaCita.addActionListener(citasControlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumCitas = new javax.swing.JTextField();
        txtIdenMedico = new javax.swing.JTextField();
        txtEstaCita = new javax.swing.JTextField();
        txtObserCita = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdtFechaCita = new com.toedter.calendar.JDateChooser();
        txtHoraCita = new javax.swing.JTextField();
        txtNumeConsultorio = new javax.swing.JTextField();
        txtIdenPaciente = new javax.swing.JTextField();
        btnRegisCita = new javax.swing.JButton();
        btnNuevaCita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar citas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numero de cita");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel3.setText("Fecha cita");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel4.setText("Hora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel5.setText("Observaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel1.add(txtNumCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, -1));
        jPanel1.add(txtIdenMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, -1));
        jPanel1.add(txtEstaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, -1));
        jPanel1.add(txtObserCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        jLabel7.setText("Identificación del medico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setText("Numero consultorio ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel9.setText("Identificación paciente");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        jPanel1.add(jdtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        txtHoraCita.setText("00:00");
        jPanel1.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, -1));
        jPanel1.add(txtNumeConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, -1));
        jPanel1.add(txtIdenPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, -1));

        btnRegisCita.setText("Registrar");
        jPanel1.add(btnRegisCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        btnNuevaCita.setText("Nuevo");
        jPanel1.add(btnNuevaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/FondoConsulCitas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 580, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNuevaCita;
    public javax.swing.JButton btnRegisCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public com.toedter.calendar.JDateChooser jdtFechaCita;
    public javax.swing.JTextField txtEstaCita;
    public javax.swing.JTextField txtHoraCita;
    public javax.swing.JTextField txtIdenMedico;
    public javax.swing.JTextField txtIdenPaciente;
    public javax.swing.JTextField txtNumCitas;
    public javax.swing.JTextField txtNumeConsultorio;
    public javax.swing.JTextField txtObserCita;
    // End of variables declaration//GEN-END:variables
}
