/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author maria
 */
public class RegTratamientoInternalFrame extends javax.swing.JInternalFrame {

    private Controlador.TratamientoControl tratamientoControlador;
    
    public RegTratamientoInternalFrame() {
        initComponents();
        tratamientoControlador  = new Controlador.TratamientoControl(this);
        btnRegTratamiento.addActionListener(tratamientoControlador);
        btnNuevTratamiento.addActionListener(tratamientoControlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodiTratamiento = new javax.swing.JTextField();
        txtDesTratamiento = new javax.swing.JTextField();
        txtIdenPaciente = new javax.swing.JTextField();
        btnRegTratamiento = new javax.swing.JButton();
        btnNuevTratamiento = new javax.swing.JButton();
        jdFeAsignada = new com.toedter.calendar.JDateChooser();
        jdFeInicio = new com.toedter.calendar.JDateChooser();
        jdFeFinal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro tratamiento");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo tratamiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel3.setText("Fecha asignada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel4.setText("Fecha inicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel5.setText("Fecha final");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel6.setText("Descripcion del tratamiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setText("Identificacion del paciente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtCodiTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, -1));
        jPanel1.add(txtDesTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, -1));
        jPanel1.add(txtIdenPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 80, -1));

        btnRegTratamiento.setText("Registrar");
        jPanel1.add(btnRegTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnNuevTratamiento.setText("Nuevo");
        jPanel1.add(btnNuevTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));
        jPanel1.add(jdFeAsignada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));
        jPanel1.add(jdFeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));
        jPanel1.add(jdFeFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/calendario-tratamiento-medico-gestion-tiempo_23-2148438973.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 540, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNuevTratamiento;
    public javax.swing.JButton btnRegTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public com.toedter.calendar.JDateChooser jdFeAsignada;
    public com.toedter.calendar.JDateChooser jdFeFinal;
    public com.toedter.calendar.JDateChooser jdFeInicio;
    public javax.swing.JTextField txtCodiTratamiento;
    public javax.swing.JTextField txtDesTratamiento;
    public javax.swing.JTextField txtIdenPaciente;
    // End of variables declaration//GEN-END:variables
}
