/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class ConsCitasInternalFrame extends javax.swing.JInternalFrame {

   public Controlador.GestorCitasControl gestorcitasControl;
    private DefaultTableModel tabla;
    public ConsCitasInternalFrame() {
        initComponents();
        gestorcitasControl =new Controlador.GestorCitasControl(this);
        String titulosTabla[]={"Codigo","Nombres"};     
        tabla=new DefaultTableModel(null, titulosTabla);
        jtCitas.setModel(tabla);
        btnBusCita.addActionListener(gestorcitasControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrBusCitas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrNumeCita = new javax.swing.JRadioButton();
        jrEstaCitas = new javax.swing.JRadioButton();
        jrFechaCita = new javax.swing.JRadioButton();
        jrIdenMedico = new javax.swing.JRadioButton();
        jrHoraCita = new javax.swing.JRadioButton();
        jrObserCitas = new javax.swing.JRadioButton();
        jrIdenPaciente = new javax.swing.JRadioButton();
        jrCodiConsultorio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtValorCita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCitas = new javax.swing.JTable();
        btnBusCita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar citas");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngrBusCitas.add(jrNumeCita);
        jrNumeCita.setText("Numero de cita");
        jrNumeCita.setOpaque(false);
        jPanel1.add(jrNumeCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btngrBusCitas.add(jrEstaCitas);
        jrEstaCitas.setText("Estado");
        jrEstaCitas.setOpaque(false);
        jPanel1.add(jrEstaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        btngrBusCitas.add(jrFechaCita);
        jrFechaCita.setText("Fecha");
        jrFechaCita.setOpaque(false);
        jPanel1.add(jrFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        btngrBusCitas.add(jrIdenMedico);
        jrIdenMedico.setText("identificacion medico");
        jrIdenMedico.setOpaque(false);
        jPanel1.add(jrIdenMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        btngrBusCitas.add(jrHoraCita);
        jrHoraCita.setText("Hora");
        jrHoraCita.setOpaque(false);
        jPanel1.add(jrHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btngrBusCitas.add(jrObserCitas);
        jrObserCitas.setText("Observaciones");
        jrObserCitas.setOpaque(false);
        jPanel1.add(jrObserCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        btngrBusCitas.add(jrIdenPaciente);
        jrIdenPaciente.setText("Identificacion paciente");
        jrIdenPaciente.setOpaque(false);
        jPanel1.add(jrIdenPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btngrBusCitas.add(jrCodiConsultorio);
        jrCodiConsultorio.setText("Codigo consultorio");
        jrCodiConsultorio.setOpaque(false);
        jPanel1.add(jrCodiConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("Valor a buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txtValorCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 110, -1));

        jtCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtCitas.setOpaque(false);
        jScrollPane1.setViewportView(jtCitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 90));

        btnBusCita.setText("Buscar");
        jPanel1.add(btnBusCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/FondoConsulCitas.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 540, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBusCita;
    private javax.swing.ButtonGroup btngrBusCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton jrCodiConsultorio;
    public javax.swing.JRadioButton jrEstaCitas;
    public javax.swing.JRadioButton jrFechaCita;
    public javax.swing.JRadioButton jrHoraCita;
    public javax.swing.JRadioButton jrIdenMedico;
    public javax.swing.JRadioButton jrIdenPaciente;
    public javax.swing.JRadioButton jrNumeCita;
    public javax.swing.JRadioButton jrObserCitas;
    public javax.swing.JTable jtCitas;
    public javax.swing.JTextField txtValorCita;
    // End of variables declaration//GEN-END:variables
}
