/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author maria
 */
public class RegConsulInternalFrame extends javax.swing.JInternalFrame {

    private Controlador.ConsultorioControl consultorioControlador;
    
    public RegConsulInternalFrame() {
        initComponents();
        consultorioControlador  = new Controlador.ConsultorioControl(this);
        btnRegiConsultorio.addActionListener(consultorioControlador);
        btnNueConsultorio.addActionListener(consultorioControlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodiConsultorio = new javax.swing.JTextField();
        txtNomConsultorio = new javax.swing.JTextField();
        btnRegiConsultorio = new javax.swing.JButton();
        btnNueConsultorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar consultorio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo de consultorio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setText("Nombre de consultorio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));
        jPanel1.add(txtCodiConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 90, -1));
        jPanel1.add(txtNomConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 90, -1));

        btnRegiConsultorio.setText("Registrar");
        jPanel1.add(btnRegiConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        btnNueConsultorio.setText("Nuevo");
        jPanel1.add(btnNueConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/primer-plano-medicina-empaquetada-blister-estetoscopio-bloc-notas-espiral-sobre-fondo-azul_23-2148214025.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 540, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNueConsultorio;
    public javax.swing.JButton btnRegiConsultorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCodiConsultorio;
    public javax.swing.JTextField txtNomConsultorio;
    // End of variables declaration//GEN-END:variables
}
