/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author maria
 */
public class RegMedicoInternalFrame extends javax.swing.JInternalFrame {

    private Controlador.MedicoControl medicoControlador;
    
    public RegMedicoInternalFrame() {
        initComponents();
        medicoControlador  = new Controlador.MedicoControl(this);
        btnRegistroMe.addActionListener(medicoControlador);
        btnMeNuevo.addActionListener(medicoControlador);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMeIdentificacion = new javax.swing.JTextField();
        txtMeNombre = new javax.swing.JTextField();
        txtMeApellido = new javax.swing.JTextField();
        btnRegistroMe = new javax.swing.JButton();
        btnMeNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro Medicos");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Identificacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));
        getContentPane().add(txtMeIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, -1));
        getContentPane().add(txtMeNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, -1));
        getContentPane().add(txtMeApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));

        btnRegistroMe.setText("Registrar");
        getContentPane().add(btnRegistroMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 80, -1));

        btnMeNuevo.setText("Nuevo");
        getContentPane().add(btnMeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_citas1/doctor-estetoscopio-formulario-medico_23-2148454284.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 550, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMeNuevo;
    public javax.swing.JButton btnRegistroMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtMeApellido;
    public javax.swing.JTextField txtMeIdentificacion;
    public javax.swing.JTextField txtMeNombre;
    // End of variables declaration//GEN-END:variables
}
